#!/bin/bash

GREEN="\\033[1;32m"
WHITE="\\033[0;39m"
RED="\\033[1;31m"
CYAN="\\033[1;36m"
YELLOW="\\033[1;33m"
BLUE="\\033[1;34m"


DATE=$(date +%Y-%m-%d:%H:%M:%S)


echo $DATE

cmd="dnf"
#cmd="apt-get"

echo "[SCRIPT] : UPDATING REPOS..."
/usr/bin/"$cmd" update
echo "[SCRIPT] : SOFT UPGRADING..."
/usr/bin/"$cmd" upgrade -y
echo "[SCRIPT] : HARD UPGRADING..."
/usr/bin/"$cmd" dist-upgrade -y

echo "[SCRIPT] : INSTALLATION SUCCESS !!!"








