#!/bin/bash

GREEN="\\033[1;32m"
WHITE="\\033[0;39m"
RED="\\033[1;31m"
CYAN="\\033[1;36m"
YELLOW="\\033[1;33m"
BLUE="\\033[1;34m"
OK=""
DATE=$(date +%Y-%m-%d:%H:%M:%S)

#-----------------------------------------------FUNCTIONS-------------------------------------------------------

function VboxGuest
{
    echo -e "$YELLOW""[SCRIPT] : Starting VBox Guest Additions install...""$WHITE"
    /usr/bin/dnf update kernel -y
    if [ ! -d "/media/VirtualBoxGuestAdditions" ];then
        /usr/bin/mkdir /media/VirtualBoxGuestAdditions
    fi
    if mount | grep /media/VirtualBoxGuestAdditions > /dev/null; then
        echo "Media already mounted"
    else
        echo "Media mounting now..."
        /usr/bin/mount -r /dev/cdrom /media/VirtualBoxGuestAdditions
    fi
    /usr/bin/dnf install gcc kernel-devel kernel-headers dkms make bzip2 perl -y
    $(KERN_DIR=/usr/src/kernels/`uname -r`)
    $(export KERN_DIR)
    bash /media/VirtualBoxGuestAdditions/./VBoxLinuxAdditions.run
}

function FullUpdate
{
    echo -e "$YELLOW""[SCRIPT] : UPDATING REPOS...""$WHITE"
    /usr/bin/dnf update -y
    echo -e "$YELLOW""[SCRIPT] : SOFT UPGRADING...""$WHITE"
    /usr/bin/dnf upgrade -y
    echo -e "$YELLOW""[SCRIPT] : HARD UPGRADING...""$WHITE"
    /usr/bin/dnf dist-upgrade -y
}

function zshInstall
{
    echo -e "$YELLOW""[SCRIPT] : INSTALLING ZSH, CURL and GIT...""$WHITE"
    /usr/bin/dnf install zsh -y
    /usr/bin/dnf install curl -y
    /usr/bin/dnf install git -y
    echo -e "$YELLOW""[SCRIPT] : INSTALLING OH-MYZ.SH FOR ROOT...""$WHITE"
    /usr/bin/curl -L http://install.ohmyz.sh | sh
    /bin/sed -i "s/ZSH_THEME=\".*\"/ZSH_THEME=\"dallas\"/g" "$HOME""/.zshrc"
    if [ "$SUDO_USER" != "" ];then
        echo -e "$YELLOW""[SCRIPT] : INSTALLING OH-MYZ.SH FOR USER...""$WHITE"
        su - $SUDO_USER -c "/usr/bin/curl -L http://install.ohmyz.sh | sh"
        /bin/sed -i "s/ZSH_THEME=\".*\"/ZSH_THEME=\"gnzh\"/g" "/home/""$SUDO_USER""/.zshrc"
        /bin/chsh -s /bin/zsh $SUDO_USER
    fi
}

function FedoFreshInstall
{
    echo -e "$YELLOW""[SCRIPT] : INSTALLING USUAL SOFTWARES FOR FRESH FEDORA INSTALL...""$WHITE"
    /usr/bin/hostname "$HOST"
    /usr/bin/rpm -ivh http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-26.noarch.rpm
    /usr/bin/dnf install vlc -y
    /usr/bin/dnf install unzip -y
    /usr/bin/dnf install icedtea-web java-openjdk -y
    /usr/bin/dnf install gimp -y
    /usr/bin/dnf install filezilla -y
    echo "[google-chrome]
name=google-chrome
baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub" > /etc/yum.repos.d/google-chrome.repo
}

function Fedora
{
    echo -e "$BLUE"
    read -p "Is it VBOX Virtual Machine ? [y/n] : " ANSWER1
    if [ $ANSWER1 = "y" ];then
        echo -e "$RED""[WARNING] : PLEASE, INSERT GUEST ADDITIONS ISO-CD FROM VBox GUI !!!"
        read -p "OK ? [y/n] : " OK
    fi
    echo -e "$BLUE"
    read -p "Install ZSH ? [y/n] : " ANSWER2
    read -p "Is it a fresh Fedora install ? [y/n] : " ANSWER3
    if [ $ANSWER3 = "y" ];then
        read -p "What hostname would you like ? : " HOST
    fi
    FullUpdate
    if [ "$OK" = "y" ];then
        VboxGuest
    fi
    if [ $ANSWER2 = "y" ];then
        zshInstall
    fi
    if [ $ANSWER3 = "y" ];then
        FedoFreshInstall
        FullUpdate
    fi
}

function checkUser
{
    if [ "$SUDO_USER" = "" ];then
        echo -e "$RED""[WARNING] : IT SEEMS YOU EXECUTED SCRIPT AS ROOT, WE RECOMMAND YOU TO EXECUTE SCRIPT AS STANDARD USER WITH SUDO COMMAND..."
        read -p "Do you want to continue anyway ? [y/n] : " ANSWER
        if [ $ANSWER = "n" ];then
            exit
        fi
    fi
}

#-----------------------------------------------SCRIPT-----------------------------------------------------------

echo -e "$RED""Executing Fedora 26 Install Script : "$DATE
checkUser
Fedora
echo -e "$GREEN""[SCRIPT] : INSTALLATION SUCCESS !!!""$WHITE"
echo -e "$GREEN""[SCRIPT] : Please reboot your system""$WHITE"

#----------------------------------------------------------------------------------------------------------------






